<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_g_nI8HCmEeyXNsFPbLjerQ" name="GlavniDijagram" author="Hope" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_g_nI8XCmEeyXNsFPbLjerQ" name="InvertovanaAukcija">
      <elements xmi:type="process:Lane" xmi:id="_g_nI8nCmEeyXNsFPbLjerQ" name="Klijent" actor="_OzhvUJGdEeyEgKb-nuTpFA">
        <elements xmi:type="process:StartEvent" xmi:id="_g_nI83CmEeyXNsFPbLjerQ" name="Zahtev za nabavku" outgoing="_g_nJCHCmEeyXNsFPbLjerQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g_nI9HCmEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g_nI9XCmEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g_nI9nCmEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_g_nI93CmEeyXNsFPbLjerQ" name="Unos podataka o zahtevu" outgoing="_WCRKQHCpEeyXNsFPbLjerQ" incoming="_g_nJCHCmEeyXNsFPbLjerQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g_nI-HCmEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g_nI-XCmEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g_nI-nCmEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_g_nI-3CmEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_g_nI_HCmEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_g_nI_XCmEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_g_nI_nCmEeyXNsFPbLjerQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_g_nI_3CmEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_g_nJAHCmEeyXNsFPbLjerQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_g_nJAXCmEeyXNsFPbLjerQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_g_nJAnCmEeyXNsFPbLjerQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_g_nJA3CmEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_WCLDoHCpEeyXNsFPbLjerQ" name="Algoritam formira listu firmi kojima ce da prosledi zahtev" outgoing="_arc74HCpEeyXNsFPbLjerQ" incoming="_WCRKQHCpEeyXNsFPbLjerQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WCLqsXCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WCLqsHCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WCLqsnCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WCLqs3CpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WCLqtHCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WCLqtXCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WCLqt3CpEeyXNsFPbLjerQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WCLqtnCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_chG18HCpEeyXNsFPbLjerQ" name="Salje se email selektovanim firmama" incoming="_chNjoHCpEeyXNsFPbLjerQ _69NzEHCpEeyXNsFPbLjerQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_chG18nCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_chG18XCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_chG183CpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_chG19HCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_chG19XCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_chG19nCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_chG1-HCpEeyXNsFPbLjerQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_chG193CpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:IntermediateErrorCatchEvent" xmi:id="_IO_LIHCqEeyXNsFPbLjerQ" name="Error2" outgoing="_oIfTUHCqEeyXNsFPbLjerQ"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_fOYUgHCpEeyXNsFPbLjerQ" name="End1" incoming="_5q0XEHCpEeyXNsFPbLjerQ _Il_OQHO9EeyZqK-Za-7q-g _cRUJYHO9EeyZqK-Za-7q-g _Ki8i0HPAEeyZqK-Za-7q-g _Go5dMHPCEeyZqK-Za-7q-g _N7K0IHPGEeySYZ5sg-RwCQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fOY7kXCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fOY7kHCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fOY7knCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_uyil8HCpEeyXNsFPbLjerQ" name="Korisniku se salje email obavestenje" incoming="_uyoskHCpEeyXNsFPbLjerQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_uyjNAXCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_uyjNAHCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_uyjNAnCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_uyjNA3CpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_uyjNBHCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_uyjNBXCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_uyjNB3CpEeyXNsFPbLjerQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_uyjNBnCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:IntermediateErrorCatchEvent" xmi:id="_EF3ZoHCqEeyXNsFPbLjerQ" name="Error1" outgoing="_FkEdAHCqEeyXNsFPbLjerQ"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__6MN8HCqEeyXNsFPbLjerQ" name="Korisnik odlucuje da li ce da otkaze zahtev" outgoing="_49A14HCpEeyXNsFPbLjerQ" incoming="_FkEdAHCqEeyXNsFPbLjerQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1vABwXCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1vABwHCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1vABwnCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1vABw3CpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1vABxHCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1vABxXCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1vABx3CpEeyXNsFPbLjerQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1vABxnCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__6M1CXCqEeyXNsFPbLjerQ">
            <targetForm xmi:type="expression:Expression" xmi:id="__6M1CnCqEeyXNsFPbLjerQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__6M1CHCqEeyXNsFPbLjerQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__6M1C3CqEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Mz-uIHO8EeyZqK-Za-7q-g" name="Klijent bira ponudu" outgoing="_jD20MHO9EeyZqK-Za-7q-g" incoming="_46JLAHO9EeyZqK-Za-7q-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_InzBkXO8EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_InzBkHO8EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_InzBknO8EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_InzBk3O8EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_InzBlHO8EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_InzBlXO8EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_InzBl3O8EeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_InzBlnO8EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Mz_8SHO8EeyZqK-Za-7q-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_Mz_8SXO8EeyZqK-Za-7q-g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Mz_8R3O8EeyZqK-Za-7q-g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Mz_8SnO8EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_NX4scHO8EeyZqK-Za-7q-g" name="Klijent odlucuje da li ce odabrati neku ponudu, produziti rok ili otkazati" outgoing="_ltmTEHO8EeyZqK-Za-7q-g" incoming="_r0hqgHO7EeyZqK-Za-7q-g _6L2f8HO8EeyZqK-Za-7q-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r0ZusXO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r0ZusHO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r0ZusnO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_r0Zus3O7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_r0ZutHO7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_r0ZutXO7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_r0Zut3O7EeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_r0ZutnO7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_NX5TiXO8EeyZqK-Za-7q-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_NX5TinO8EeyZqK-Za-7q-g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_NX5TiHO8EeyZqK-Za-7q-g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_NX5Ti3O8EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_h25m8HO_EeyZqK-Za-7q-g" name="Klijent trazi dodatne informacije" outgoing="_in8pYHO_EeyZqK-Za-7q-g" incoming="_dctTkHO_EeyZqK-Za-7q-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dcnM8XO_EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dcnM8HO_EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dcnM8nO_EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dcnM83O_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dcnM9HO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dcnM9XO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dcnM93O_EeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dcnM9nO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_h26OCXO_EeyZqK-Za-7q-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_h26OCnO_EeyZqK-Za-7q-g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_h26OCHO_EeyZqK-Za-7q-g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_h26OC3O_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_EIMs8HPAEeyZqK-Za-7q-g" name="Klijent donosi odluku oko zahteva" outgoing="_JMj-sHPAEeyZqK-Za-7q-g" incoming="_DNsMgHPAEeyZqK-Za-7q-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DNms8XPAEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DNms8HPAEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DNms8nPAEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DNms83PAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DNms9HPAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_DNms9XPAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_DNms93PAEeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_DNms9nPAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_EINUCXPAEeyZqK-Za-7q-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_EINUCnPAEeyZqK-Za-7q-g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_EINUCHPAEeyZqK-Za-7q-g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_EINUC3PAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_KBCvoHPAEeyZqK-Za-7q-g" name="Gateway8" outgoing="_Ki8i0HPAEeyZqK-Za-7q-g _g3uzgHPAEeyZqK-Za-7q-g _boB6wHSMEey81q0uuuC8TQ" incoming="_JMj-sHPAEeyZqK-Za-7q-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JMefInPAEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JMefIXPAEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JMefI3PAEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_0c8fkHPAEeyZqK-Za-7q-g" name="sistem salje zahtev odgovarajucim firmama" outgoing="_8iSPAHPAEeyZqK-Za-7q-g" incoming="_nfGF4HO8EeyZqK-Za-7q-g _oIfTUHCqEeyXNsFPbLjerQ _ft6zIHO9EeyZqK-Za-7q-g _boB6wHSMEey81q0uuuC8TQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s86coXPAEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s86coHPAEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s86conPAEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s86co3PAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s86cpHPAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s86cpXPAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s86cp3PAEeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s86cpnPAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_B4lv4HPCEeyZqK-Za-7q-g" name="Klijent potvrdjuje zavrsetak posla i ocenjuje firmu" outgoing="_Go5dMHPCEeyZqK-Za-7q-g" incoming="_ACph8HPCEeyZqK-Za-7q-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7Fkj8nPBEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7Fkj8XPBEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7Fkj83PBEeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7Fkj9HPBEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7Fkj9XPBEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7Fkj9nPBEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7Fkj-HPBEeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7Fkj93PBEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_B4mW9HPCEeyZqK-Za-7q-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_B4mW9XPCEeyZqK-Za-7q-g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_B4mW83PCEeyZqK-Za-7q-g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_B4mW9nPCEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_TaXAsHPGEeySYZ5sg-RwCQ" name="obavestava se korisnik" outgoing="_N7K0IHPGEeySYZ5sg-RwCQ" incoming="_fOd0EHCpEeyXNsFPbLjerQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_J4K4wXPGEeySYZ5sg-RwCQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_J4K4wHPGEeySYZ5sg-RwCQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_J4K4wnPGEeySYZ5sg-RwCQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_J4K4w3PGEeySYZ5sg-RwCQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_J4K4xHPGEeySYZ5sg-RwCQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_J4K4xXPGEeySYZ5sg-RwCQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_J4K4x3PGEeySYZ5sg-RwCQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_J4K4xnPGEeySYZ5sg-RwCQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_wqbd4HSJEey81q0uuuC8TQ" name="Gateway1" outgoing="_chNjoHCpEeyXNsFPbLjerQ _fOd0EHCpEeyXNsFPbLjerQ _uyoskHCpEeyXNsFPbLjerQ" incoming="_arc74HCpEeyXNsFPbLjerQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_arXcUXCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_arXcUHCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_arXcUnCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_xlzhAHSJEey81q0uuuC8TQ" name="Gateway2" outgoing="_5q0XEHCpEeyXNsFPbLjerQ _69NzEHCpEeyXNsFPbLjerQ" incoming="_49A14HCpEeyXNsFPbLjerQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_487WUnCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_487WUXCpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_487WU3CpEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ySgO8HSJEey81q0uuuC8TQ" name="Gateway6" outgoing="_cRUJYHO9EeyZqK-Za-7q-g _jEqh8HO8EeyZqK-Za-7q-g _ft6zIHO9EeyZqK-Za-7q-g" incoming="_jD20MHO9EeyZqK-Za-7q-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jDxUoXO9EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jDxUoHO9EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jDxUonO9EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_y53J4HSJEey81q0uuuC8TQ" name="Gateway7" outgoing="_LPO2gHO_EeyZqK-Za-7q-g _dctTkHO_EeyZqK-Za-7q-g" incoming="_jEqh8HO8EeyZqK-Za-7q-g _mgIjQHO8EeyZqK-Za-7q-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xQGbAXO-EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xQGbAHO-EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xQGbAnO-EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_z0rMUHSJEey81q0uuuC8TQ" name="Gateway5" outgoing="_mgIjQHO8EeyZqK-Za-7q-g _nfGF4HO8EeyZqK-Za-7q-g _Il_OQHO9EeyZqK-Za-7q-g" incoming="_ltmTEHO8EeyZqK-Za-7q-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ltflYXO8EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ltflYHO8EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ltflYnO8EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ZkxLMHCqEeyXNsFPbLjerQ" name="Agent" actor="_RG-YoJGdEeyEgKb-nuTpFA">
        <elements xmi:type="process:Task" xmi:id="__QUKgHCqEeyXNsFPbLjerQ" name="Prihvatanje ili odbijanje zahteva" outgoing="_BSA8gHCrEeyXNsFPbLjerQ" incoming="_8iSPAHPAEeyZqK-Za-7q-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_i1vAQXCqEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_i1vAQHCqEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_i1vAQnCqEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_i1vAQ3CqEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_i1vARHCqEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_i1vARXCqEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_i1vAR3CqEeyXNsFPbLjerQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_i1vARnCqEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__QUxkXCqEeyXNsFPbLjerQ">
            <targetForm xmi:type="expression:Expression" xmi:id="__QUxknCqEeyXNsFPbLjerQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__QUxkHCqEeyXNsFPbLjerQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__QUxk3CqEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_CNZmsHCrEeyXNsFPbLjerQ" name="End2" incoming="_CNfGQHCrEeyXNsFPbLjerQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CNaNwXCrEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CNaNwHCrEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CNaNwnCrEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_F1iyEHCrEeyXNsFPbLjerQ" name="Gateway3" outgoing="_CNfGQHCrEeyXNsFPbLjerQ _DZe_UHCrEeyXNsFPbLjerQ" incoming="_BSA8gHCrEeyXNsFPbLjerQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BR8EAnCrEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BR8EAXCrEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BR8EA3CrEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_vl7f0HCrEeyXNsFPbLjerQ" name="Popunjavanje ponude" incoming="_DZe_UHCrEeyXNsFPbLjerQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DZZfwXCrEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DZZfwHCrEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DZZfwnCrEeyXNsFPbLjerQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DZZfw3CrEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DZZfxHCrEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_DZZfxXCrEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_DZZfx3CrEeyXNsFPbLjerQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_DZZfxnCrEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_wBG_8HCrEeyXNsFPbLjerQ" name="Boundary Timer1" outgoing="_NiKfQHO7EeyZqK-Za-7q-g"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vl8G6XCrEeyXNsFPbLjerQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_vl8G6nCrEeyXNsFPbLjerQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vl8G6HCrEeyXNsFPbLjerQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vl8G63CrEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_NhoTwHO7EeyZqK-Za-7q-g" name="Analiza ponuda" outgoing="_U_4OAHO7EeyZqK-Za-7q-g" incoming="_NiKfQHO7EeyZqK-Za-7q-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Nh0hAXO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Nh0hAHO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Nh0hAnO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Nh0hA3O7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Nh0hBHO7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Nh0hBXO7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Nh1IEHO7EeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Nh0hBnO7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_b87fsHO7EeyZqK-Za-7q-g" name="Obavestavanje klijenta da nema dovoljno ponuda" incoming="_b9ECkHO7EeyZqK-Za-7q-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_b88GwXO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_b88GwHO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_b88GwnO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_b88Gw3O7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_b88GxHO7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_b88t0HO7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_b88t0nO7EeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_b88t0XO7EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:IntermediateErrorCatchEvent" xmi:id="_o2AD4HO7EeyZqK-Za-7q-g" outgoing="_r0hqgHO7EeyZqK-Za-7q-g"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_0qlaUHO9EeyZqK-Za-7q-g" name="Rangiranje ponuda" outgoing="_46JLAHO9EeyZqK-Za-7q-g" incoming="_0qsvEHO9EeyZqK-Za-7q-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0qlaUnO9EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0qlaUXO9EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0qlaU3O9EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0qlaVHO9EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0qmBYHO9EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0qmBYXO9EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0qmBY3O9EeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0qmBYnO9EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_3_vtYHO_EeyZqK-Za-7q-g" name="Agent potvrdjuje ponudu i odredjuje vreme pocetka i kraja izvrsavanja" incoming="_LPO2gHO_EeyZqK-Za-7q-g _g3uzgHPAEeyZqK-Za-7q-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LPIv4XO_EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LPIv4HO_EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LPIv4nO_EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_LPIv43O_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_LPIv5HO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_LPIv5XO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_LPIv53O_EeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_LPIv5nO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_3gdecHPBEeyZqK-Za-7q-g" name="tajmer" outgoing="_ACph8HPCEeyZqK-Za-7q-g"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_3_wUdXO_EeyZqK-Za-7q-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_3_wUdnO_EeyZqK-Za-7q-g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_3_wUdHO_EeyZqK-Za-7q-g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_3_wUd3O_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4VabYHO_EeyZqK-Za-7q-g" name="Agent odgovara na zahtev" outgoing="_DNsMgHPAEeyZqK-Za-7q-g" incoming="_in8pYHO_EeyZqK-Za-7q-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_in2iwXO_EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_in2iwHO_EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_in2iwnO_EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_in2iw3O_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_in2ixHO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_in2ixXO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_in2ix3O_EeyZqK-Za-7q-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_in2ixnO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4VbphHO_EeyZqK-Za-7q-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_4VbphXO_EeyZqK-Za-7q-g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4Vbpg3O_EeyZqK-Za-7q-g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4VbphnO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_1HYxYHSJEey81q0uuuC8TQ" name="Gateway4" outgoing="_b9ECkHO7EeyZqK-Za-7q-g _6L2f8HO8EeyZqK-Za-7q-g _0qsvEHO9EeyZqK-Za-7q-g" incoming="_U_4OAHO7EeyZqK-Za-7q-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_U_xgUXO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_U_xgUHO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_U_xgUnO7EeyZqK-Za-7q-g" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_oM-7AHSKEey81q0uuuC8TQ" name="pronadjeneFirme" dataType="_g_nJHnCmEeyXNsFPbLjerQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_oM-7AXSKEey81q0uuuC8TQ" name="3" content="3" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_FPeZ0HSLEey81q0uuuC8TQ" name="zahtevPrihvacen" dataType="_g_nJHHCmEeyXNsFPbLjerQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_FPeZ0XSLEey81q0uuuC8TQ" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_UxLNIHSLEey81q0uuuC8TQ" name="ponuda" dataType="_g_nJHnCmEeyXNsFPbLjerQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_UxLNIXSLEey81q0uuuC8TQ" name="3" content="3" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_gEwaMHSLEey81q0uuuC8TQ" name="trazeneDodatneInformacije" dataType="_g_nJHHCmEeyXNsFPbLjerQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_gEwaMXSLEey81q0uuuC8TQ" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_HfgtUHSMEey81q0uuuC8TQ" name="ponuda2" dataType="_g_nJHnCmEeyXNsFPbLjerQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_HfgtUXSMEey81q0uuuC8TQ" name="3" content="3" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_hjcJQHSMEey81q0uuuC8TQ" name="ponuda3" dataType="_g_nJHnCmEeyXNsFPbLjerQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_hjcJQXSMEey81q0uuuC8TQ" name="3" content="3" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_s88YIHSMEey81q0uuuC8TQ" name="imaDovoljnoPonuda" dataType="_g_nJHnCmEeyXNsFPbLjerQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_s88YIXSMEey81q0uuuC8TQ" name="3" content="3" returnType="java.lang.Integer"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_g_nJBHCmEeyXNsFPbLjerQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_g_nJBXCmEeyXNsFPbLjerQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_g_nJBnCmEeyXNsFPbLjerQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_g_nJB3CmEeyXNsFPbLjerQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g_nJCHCmEeyXNsFPbLjerQ" target="_g_nI93CmEeyXNsFPbLjerQ" source="_g_nI83CmEeyXNsFPbLjerQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g_nJCXCmEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_g_nJCnCmEeyXNsFPbLjerQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WCRKQHCpEeyXNsFPbLjerQ" target="_WCLDoHCpEeyXNsFPbLjerQ" source="_g_nI93CmEeyXNsFPbLjerQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WCRKQXCpEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_WCRxUHCpEeyXNsFPbLjerQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_arc74HCpEeyXNsFPbLjerQ" target="_wqbd4HSJEey81q0uuuC8TQ" source="_WCLDoHCpEeyXNsFPbLjerQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_arc74XCpEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_arc74nCpEeyXNsFPbLjerQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_chNjoHCpEeyXNsFPbLjerQ" name="Postoje odgovarajuce firme" target="_chG18HCpEeyXNsFPbLjerQ" source="_wqbd4HSJEey81q0uuuC8TQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_chNjoXCpEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_chNjonCpEeyXNsFPbLjerQ" name="pronadjeneFirme == 1" content="pronadjeneFirme == 1" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fOd0EHCpEeyXNsFPbLjerQ" name="Ne postoje odgovarajuce firme" target="_TaXAsHPGEeySYZ5sg-RwCQ" source="_wqbd4HSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fOebIHCpEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_fOebIXCpEeyXNsFPbLjerQ" name="pronadjeneFirme == 3" content="pronadjeneFirme == 3" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uyoskHCpEeyXNsFPbLjerQ" name="Postoje forme, ali ih nema dovoljno" target="_uyil8HCpEeyXNsFPbLjerQ" source="_wqbd4HSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uyoskXCpEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_uyosknCpEeyXNsFPbLjerQ" name="pronadjeneFirme == 2" content="pronadjeneFirme == 2" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_49A14HCpEeyXNsFPbLjerQ" target="_xlzhAHSJEey81q0uuuC8TQ" source="__6MN8HCqEeyXNsFPbLjerQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_49A14XCpEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_49A14nCpEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5q0XEHCpEeyXNsFPbLjerQ" name="otkazan zahtev" target="_fOYUgHCpEeyXNsFPbLjerQ" source="_xlzhAHSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5q0XEXCpEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5q0XEnCpEeyXNsFPbLjerQ" name="zahtevPrihvacen == false" content="zahtevPrihvacen == false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_69NzEHCpEeyXNsFPbLjerQ" name="prihvacen zahtev" target="_chG18HCpEeyXNsFPbLjerQ" source="_xlzhAHSJEey81q0uuuC8TQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_69NzEXCpEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_69NzEnCpEeyXNsFPbLjerQ" name="zahtevPrihvacen == true" content="zahtevPrihvacen == true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FkEdAHCqEeyXNsFPbLjerQ" target="__6MN8HCqEeyXNsFPbLjerQ" source="_EF3ZoHCqEeyXNsFPbLjerQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FkFEEHCqEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_FkFEEXCqEeyXNsFPbLjerQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oIfTUHCqEeyXNsFPbLjerQ" target="_0c8fkHPAEeyZqK-Za-7q-g" source="_IO_LIHCqEeyXNsFPbLjerQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oIf6YHCqEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oIf6YXCqEeyXNsFPbLjerQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BSA8gHCrEeyXNsFPbLjerQ" target="_F1iyEHCrEeyXNsFPbLjerQ" source="__QUKgHCqEeyXNsFPbLjerQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BSBjkHCrEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_BSBjkXCrEeyXNsFPbLjerQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CNfGQHCrEeyXNsFPbLjerQ" target="_CNZmsHCrEeyXNsFPbLjerQ" source="_F1iyEHCrEeyXNsFPbLjerQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CNfGQXCrEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_CNftUHCrEeyXNsFPbLjerQ" name="odbijeno == true" content="odbijeno == true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DZe_UHCrEeyXNsFPbLjerQ" target="_vl7f0HCrEeyXNsFPbLjerQ" source="_F1iyEHCrEeyXNsFPbLjerQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DZe_UXCrEeyXNsFPbLjerQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_DZe_UnCrEeyXNsFPbLjerQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NiKfQHO7EeyZqK-Za-7q-g" target="_NhoTwHO7EeyZqK-Za-7q-g" source="_wBG_8HCrEeyXNsFPbLjerQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NiLGUHO7EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_NiLGUXO7EeyZqK-Za-7q-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_U_4OAHO7EeyZqK-Za-7q-g" target="_1HYxYHSJEey81q0uuuC8TQ" source="_NhoTwHO7EeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_U_4OAXO7EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_U_4OAnO7EeyZqK-Za-7q-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_b9ECkHO7EeyZqK-Za-7q-g" name="Nema dovoljno ponuda" target="_b87fsHO7EeyZqK-Za-7q-g" source="_1HYxYHSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_b9ECkXO7EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_b9ECknO7EeyZqK-Za-7q-g" name="imaDovoljnoPonuda == 2" content="imaDovoljnoPonuda == 2" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r0hqgHO7EeyZqK-Za-7q-g" target="_NX4scHO8EeyZqK-Za-7q-g" source="_o2AD4HO7EeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r0iRkHO7EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_r0iRkXO7EeyZqK-Za-7q-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jEqh8HO8EeyZqK-Za-7q-g" name="odabrana ponuda" target="_y53J4HSJEey81q0uuuC8TQ" source="_ySgO8HSJEey81q0uuuC8TQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jErJAHO8EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_jErJAXO8EeyZqK-Za-7q-g" name="ponuda == 1" content="ponuda == 1" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ltmTEHO8EeyZqK-Za-7q-g" target="_z0rMUHSJEey81q0uuuC8TQ" source="_NX4scHO8EeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ltm6IHO8EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_ltm6IXO8EeyZqK-Za-7q-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mgIjQHO8EeyZqK-Za-7q-g" target="_y53J4HSJEey81q0uuuC8TQ" source="_z0rMUHSJEey81q0uuuC8TQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mgJKUHO8EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_mgJKUXO8EeyZqK-Za-7q-g" name="ponuda2 == 1" content="ponuda2 == 1" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nfGF4HO8EeyZqK-Za-7q-g" name="produzen rok za ponude" target="_0c8fkHPAEeyZqK-Za-7q-g" source="_z0rMUHSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nfGs8HO8EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_nfGs8XO8EeyZqK-Za-7q-g" name="ponuda2 == 2" content="ponuda2 == 2" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6L2f8HO8EeyZqK-Za-7q-g" name="nema ponuda" target="_NX4scHO8EeyZqK-Za-7q-g" source="_1HYxYHSJEey81q0uuuC8TQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6L2f8XO8EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_6L2f8nO8EeyZqK-Za-7q-g" name="imaDovoljnoPonuda == 3" content="imaDovoljnoPonuda == 3" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Il_OQHO9EeyZqK-Za-7q-g" name="otkazan zahtev" target="_fOYUgHCpEeyXNsFPbLjerQ" source="_z0rMUHSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Il_1UHO9EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Il_1UXO9EeyZqK-Za-7q-g" name="ponuda2 == 3" content="ponuda2 == 3" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cRUJYHO9EeyZqK-Za-7q-g" name="otkazan zahtev" target="_fOYUgHCpEeyXNsFPbLjerQ" source="_ySgO8HSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cRV-kHO9EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_cRV-kXO9EeyZqK-Za-7q-g" name="ponuda == 3" content="ponuda == 3" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ft6zIHO9EeyZqK-Za-7q-g" name="produzen rok" target="_0c8fkHPAEeyZqK-Za-7q-g" source="_ySgO8HSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ft7aMHO9EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_ft7aMXO9EeyZqK-Za-7q-g" name="ponuda == 2" content="ponuda == 2" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jD20MHO9EeyZqK-Za-7q-g" target="_ySgO8HSJEey81q0uuuC8TQ" source="_Mz-uIHO8EeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jD20MXO9EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_jD20MnO9EeyZqK-Za-7q-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0qsvEHO9EeyZqK-Za-7q-g" name="ima dovoljno ponuda" target="_0qlaUHO9EeyZqK-Za-7q-g" source="_1HYxYHSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0qtWIHO9EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_0qtWIXO9EeyZqK-Za-7q-g" name="imaDovoljnoPonuda == 1" content="imaDovoljnoPonuda == 1" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_46JLAHO9EeyZqK-Za-7q-g" target="_Mz-uIHO8EeyZqK-Za-7q-g" source="_0qlaUHO9EeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_46JyEHO9EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_46JyEXO9EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LPO2gHO_EeyZqK-Za-7q-g" name="Prihvacena ponuda" target="_3_vtYHO_EeyZqK-Za-7q-g" source="_y53J4HSJEey81q0uuuC8TQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LPPdkHO_EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_LPPdkXO_EeyZqK-Za-7q-g" name="trazeneDodatneInformacije == false" content="trazeneDodatneInformacije == false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dctTkHO_EeyZqK-Za-7q-g" target="_h25m8HO_EeyZqK-Za-7q-g" source="_y53J4HSJEey81q0uuuC8TQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dct6oHO_EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_dct6oXO_EeyZqK-Za-7q-g" name="trazeneDodatneInformacije == true" content="trazeneDodatneInformacije == true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_in8pYHO_EeyZqK-Za-7q-g" target="_4VabYHO_EeyZqK-Za-7q-g" source="_h25m8HO_EeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_in8pYXO_EeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_in8pYnO_EeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DNsMgHPAEeyZqK-Za-7q-g" target="_EIMs8HPAEeyZqK-Za-7q-g" source="_4VabYHO_EeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DNszkHPAEeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_DNszkXPAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JMj-sHPAEeyZqK-Za-7q-g" target="_KBCvoHPAEeyZqK-Za-7q-g" source="_EIMs8HPAEeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JMj-sXPAEeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_JMj-snPAEeyZqK-Za-7q-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ki8i0HPAEeyZqK-Za-7q-g" name="otkazan zahtev" target="_fOYUgHCpEeyXNsFPbLjerQ" source="_KBCvoHPAEeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ki8i0XPAEeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ki8i0nPAEeyZqK-Za-7q-g" name="ponuda3 = 3" content="ponuda3 = 3" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g3uzgHPAEeyZqK-Za-7q-g" name="odabrana ponuda" target="_3_vtYHO_EeyZqK-Za-7q-g" source="_KBCvoHPAEeyZqK-Za-7q-g" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g3wosHPAEeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_g3wosXPAEeyZqK-Za-7q-g" name="ponuda3 == 1" content="ponuda3 == 1" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8iSPAHPAEeyZqK-Za-7q-g" target="__QUKgHCqEeyXNsFPbLjerQ" source="_0c8fkHPAEeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8iS2EHPAEeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_8iS2EXPAEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ACph8HPCEeyZqK-Za-7q-g" target="_B4lv4HPCEeyZqK-Za-7q-g" source="_3gdecHPBEeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ACph8XPCEeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_ACph8nPCEeyZqK-Za-7q-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Go5dMHPCEeyZqK-Za-7q-g" target="_fOYUgHCpEeyXNsFPbLjerQ" source="_B4lv4HPCEeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Go5dMXPCEeyZqK-Za-7q-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Go5dMnPCEeyZqK-Za-7q-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_N7K0IHPGEeySYZ5sg-RwCQ" target="_fOYUgHCpEeyXNsFPbLjerQ" source="_TaXAsHPGEeySYZ5sg-RwCQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_N7K0IXPGEeySYZ5sg-RwCQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_N7LbMHPGEeySYZ5sg-RwCQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_boB6wHSMEey81q0uuuC8TQ" target="_0c8fkHPAEeyZqK-Za-7q-g" source="_KBCvoHPAEeyZqK-Za-7q-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_boCh0HSMEey81q0uuuC8TQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_boCh0XSMEey81q0uuuC8TQ" name="ponuda3 == 2" content="ponuda3 == 2" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_OzhvUJGdEeyEgKb-nuTpFA" name="Klijent" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_RG-YoJGdEeyEgKb-nuTpFA" name="Agent"/>
      <actors xmi:type="process:Actor" xmi:id="_VaCJQJGdEeyEgKb-nuTpFA" name="Administrator"/>
      <contract xmi:type="process:Contract" xmi:id="_g_nJDHCmEeyXNsFPbLjerQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g_nJDXCmEeyXNsFPbLjerQ">
        <name xmi:type="expression:Expression" xmi:id="_g_nJDnCmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g_nJD3CmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g_nJEHCmEeyXNsFPbLjerQ">
        <name xmi:type="expression:Expression" xmi:id="_g_nJEXCmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g_nJEnCmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g_nJE3CmEeyXNsFPbLjerQ">
        <name xmi:type="expression:Expression" xmi:id="_g_nJFHCmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g_nJFXCmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g_nJFnCmEeyXNsFPbLjerQ">
        <name xmi:type="expression:Expression" xmi:id="_g_nJF3CmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g_nJGHCmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g_nJGXCmEeyXNsFPbLjerQ">
        <name xmi:type="expression:Expression" xmi:id="_g_nJGnCmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g_nJG3CmEeyXNsFPbLjerQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_g_nJHHCmEeyXNsFPbLjerQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_g_nJHXCmEeyXNsFPbLjerQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_g_nJHnCmEeyXNsFPbLjerQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_g_nJH3CmEeyXNsFPbLjerQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_g_nJIHCmEeyXNsFPbLjerQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_g_nJIXCmEeyXNsFPbLjerQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_g_nJInCmEeyXNsFPbLjerQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_g_nJI3CmEeyXNsFPbLjerQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_g_nJJHCmEeyXNsFPbLjerQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_g_nJJXCmEeyXNsFPbLjerQ" type="Process" element="_g_nI8HCmEeyXNsFPbLjerQ" name="MyDiagram1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_g_nJJnCmEeyXNsFPbLjerQ" type="2007" element="_g_nI8XCmEeyXNsFPbLjerQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_g_nJJ3CmEeyXNsFPbLjerQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_g_nJKHCmEeyXNsFPbLjerQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_g_nJKXCmEeyXNsFPbLjerQ" type="3007" element="_g_nI8nCmEeyXNsFPbLjerQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_g_nJKnCmEeyXNsFPbLjerQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_g_nJK3CmEeyXNsFPbLjerQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_g_nJLHCmEeyXNsFPbLjerQ" type="3005" element="_g_nI93CmEeyXNsFPbLjerQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_g_nJLXCmEeyXNsFPbLjerQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g_nJLnCmEeyXNsFPbLjerQ" x="160" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_g_nJL3CmEeyXNsFPbLjerQ" type="3002" element="_g_nI83CmEeyXNsFPbLjerQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_g_nJMHCmEeyXNsFPbLjerQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_g_nJMXCmEeyXNsFPbLjerQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g_nJMnCmEeyXNsFPbLjerQ" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WCMRwHCpEeyXNsFPbLjerQ" type="3027" element="_WCLDoHCpEeyXNsFPbLjerQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_WCM40HCpEeyXNsFPbLjerQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WCMRwXCpEeyXNsFPbLjerQ" x="312" y="55" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_chIEEHCpEeyXNsFPbLjerQ" type="3027" element="_chG18HCpEeyXNsFPbLjerQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_chIEEnCpEeyXNsFPbLjerQ" type="5017"/>
              <children xmi:type="notation:Shape" xmi:id="_IO_yMHCqEeyXNsFPbLjerQ" type="3032" element="_IO_LIHCqEeyXNsFPbLjerQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_IPAZQHCqEeyXNsFPbLjerQ" type="5062">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_IPAZQXCqEeyXNsFPbLjerQ" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IO_yMXCqEeyXNsFPbLjerQ" x="19" y="52"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_chIEEXCpEeyXNsFPbLjerQ" x="232" y="198" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fOZioHCpEeyXNsFPbLjerQ" type="3003" element="_fOYUgHCpEeyXNsFPbLjerQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_fOZionCpEeyXNsFPbLjerQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fOZio3CpEeyXNsFPbLjerQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fOZioXCpEeyXNsFPbLjerQ" x="1182" y="230"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uyj0EHCpEeyXNsFPbLjerQ" type="3027" element="_uyil8HCpEeyXNsFPbLjerQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uykbIHCpEeyXNsFPbLjerQ" type="5017"/>
              <children xmi:type="notation:Shape" xmi:id="_EF4nwHCqEeyXNsFPbLjerQ" type="3032" element="_EF3ZoHCqEeyXNsFPbLjerQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_EF4nwnCqEeyXNsFPbLjerQ" type="5062">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_EF4nw3CqEeyXNsFPbLjerQ" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EF4nwXCqEeyXNsFPbLjerQ" x="44" y="52"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uyj0EXCpEeyXNsFPbLjerQ" x="751" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__6NcEHCqEeyXNsFPbLjerQ" type="3005" element="__6MN8HCqEeyXNsFPbLjerQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__6NcEnCqEeyXNsFPbLjerQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__6NcEXCqEeyXNsFPbLjerQ" x="939" y="58" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_M0AjUHO8EeyZqK-Za-7q-g" type="3005" element="_Mz-uIHO8EeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_M0BKYHO8EeyZqK-Za-7q-g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_M0AjUXO8EeyZqK-Za-7q-g" x="373" y="446" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NX56kHO8EeyZqK-Za-7q-g" type="3005" element="_NX4scHO8EeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NX56knO8EeyZqK-Za-7q-g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NX56kXO8EeyZqK-Za-7q-g" x="701" y="407" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_h261EHO_EeyZqK-Za-7q-g" type="3005" element="_h25m8HO_EeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_h261EnO_EeyZqK-Za-7q-g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_h261EXO_EeyZqK-Za-7q-g" x="591" y="295" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EIN7EHPAEeyZqK-Za-7q-g" type="3005" element="_EIMs8HPAEeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_EIOiIHPAEeyZqK-Za-7q-g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EIN7EXPAEeyZqK-Za-7q-g" x="878" y="635" width="133" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KBD9wHPAEeyZqK-Za-7q-g" type="3008" element="_KBCvoHPAEeyZqK-Za-7q-g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_KBD9wnPAEeyZqK-Za-7q-g" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_KBD9w3PAEeyZqK-Za-7q-g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KBD9wXPAEeyZqK-Za-7q-g" x="915" y="549" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0c9GqHPAEeyZqK-Za-7q-g" type="3027" element="_0c8fkHPAEeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0c9tsHPAEeyZqK-Za-7q-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0c9GqXPAEeyZqK-Za-7q-g" x="100" y="730" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_B4mW93PCEeyZqK-Za-7q-g" type="3005" element="_B4lv4HPCEeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_B4mW-XPCEeyZqK-Za-7q-g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_B4mW-HPCEeyZqK-Za-7q-g" x="1239" y="711" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TaY14HPGEeySYZ5sg-RwCQ" type="3027" element="_TaXAsHPGEeySYZ5sg-RwCQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TaY14nPGEeySYZ5sg-RwCQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TaY14XPGEeySYZ5sg-RwCQ" x="1147" y="75" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wtsNQHSJEey81q0uuuC8TQ" type="3008" element="_wqbd4HSJEey81q0uuuC8TQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_wttbYHSJEey81q0uuuC8TQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_wttbYXSJEey81q0uuuC8TQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wtsNQXSJEey81q0uuuC8TQ" x="535" y="68" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xl0vIHSJEey81q0uuuC8TQ" type="3008" element="_xlzhAHSJEey81q0uuuC8TQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_xl0vInSJEey81q0uuuC8TQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xl0vI3SJEey81q0uuuC8TQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xl0vIXSJEey81q0uuuC8TQ" x="954" y="217" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ySirMHSJEey81q0uuuC8TQ" type="3008" element="_ySgO8HSJEey81q0uuuC8TQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ySirMnSJEey81q0uuuC8TQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ySirM3SJEey81q0uuuC8TQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ySirMXSJEey81q0uuuC8TQ" x="400" y="334" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y54_EHSJEey81q0uuuC8TQ" type="3008" element="_y53J4HSJEey81q0uuuC8TQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_y55mIHSJEey81q0uuuC8TQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_y55mIXSJEey81q0uuuC8TQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y54_EXSJEey81q0uuuC8TQ" x="521" y="334" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_z0rzY3SJEey81q0uuuC8TQ" type="3008" element="_z0rMUHSJEey81q0uuuC8TQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_z0sacHSJEey81q0uuuC8TQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_z0sacXSJEey81q0uuuC8TQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z0rzZHSJEey81q0uuuC8TQ" x="612" y="427" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_g_nJM3CmEeyXNsFPbLjerQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_g_nJNHCmEeyXNsFPbLjerQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_g_nJNXCmEeyXNsFPbLjerQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_g_nJNnCmEeyXNsFPbLjerQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g_nJN3CmEeyXNsFPbLjerQ" x="48" y="10" width="1447" height="831"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_ZkxyQHCqEeyXNsFPbLjerQ" type="3007" element="_ZkxLMHCqEeyXNsFPbLjerQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_ZkyZUHCqEeyXNsFPbLjerQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ZkyZUXCqEeyXNsFPbLjerQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="__QUxlHCqEeyXNsFPbLjerQ" type="3005" element="__QUKgHCqEeyXNsFPbLjerQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__QUxlnCqEeyXNsFPbLjerQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__QUxlXCqEeyXNsFPbLjerQ" x="89" y="102" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_CNa00HCrEeyXNsFPbLjerQ" type="3003" element="_CNZmsHCrEeyXNsFPbLjerQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_CNa00nCrEeyXNsFPbLjerQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_CNa003CrEeyXNsFPbLjerQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CNa00XCrEeyXNsFPbLjerQ" x="859" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F1jZI3CrEeyXNsFPbLjerQ" type="3008" element="_F1iyEHCrEeyXNsFPbLjerQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_F1jZJXCrEeyXNsFPbLjerQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_F1jZJnCrEeyXNsFPbLjerQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F1jZJHCrEeyXNsFPbLjerQ" x="337" y="102" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vl8G7HCrEeyXNsFPbLjerQ" type="3005" element="_vl7f0HCrEeyXNsFPbLjerQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vl8t8HCrEeyXNsFPbLjerQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_wBHnAHCrEeyXNsFPbLjerQ" type="3043" element="_wBG_8HCrEeyXNsFPbLjerQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_wBHnAnCrEeyXNsFPbLjerQ" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_wBHnA3CrEeyXNsFPbLjerQ" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wBHnAXCrEeyXNsFPbLjerQ" x="132" y="29"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vl8G7XCrEeyXNsFPbLjerQ" x="289" y="189" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NiAuQHO7EeyZqK-Za-7q-g" type="3027" element="_NhoTwHO7EeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NiAuQnO7EeyZqK-Za-7q-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NiAuQXO7EeyZqK-Za-7q-g" x="484" y="200"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_b89U4HO7EeyZqK-Za-7q-g" type="3027" element="_b87fsHO7EeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_b89U4nO7EeyZqK-Za-7q-g" type="5017"/>
              <children xmi:type="notation:Shape" xmi:id="_o2B5EHO7EeyZqK-Za-7q-g" type="3032" element="_o2AD4HO7EeyZqK-Za-7q-g" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_o2B5EnO7EeyZqK-Za-7q-g" type="5062">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_o2B5E3O7EeyZqK-Za-7q-g" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_o2B5EXO7EeyZqK-Za-7q-g" x="47" y="-17"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b89U4XO7EeyZqK-Za-7q-g" x="930" y="204" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0qmocHO9EeyZqK-Za-7q-g" type="3027" element="_0qlaUHO9EeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0qmocnO9EeyZqK-Za-7q-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0qmocXO9EeyZqK-Za-7q-g" x="521" y="37"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3_wUeHO_EeyZqK-Za-7q-g" type="3005" element="_3_vtYHO_EeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3_wUenO_EeyZqK-Za-7q-g" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_3ghI0HPBEeyZqK-Za-7q-g" type="3064" element="_3gdecHPBEeyZqK-Za-7q-g" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_3ghv4HPBEeyZqK-Za-7q-g" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_3ghv4XPBEeyZqK-Za-7q-g" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3ghI0XPBEeyZqK-Za-7q-g"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3_wUeXO_EeyZqK-Za-7q-g" x="80" y="287" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4Vbph3O_EeyZqK-Za-7q-g" type="3005" element="_4VabYHO_EeyZqK-Za-7q-g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4VbpiXO_EeyZqK-Za-7q-g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4VbpiHO_EeyZqK-Za-7q-g" x="1049" y="59" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1HZ_gHSJEey81q0uuuC8TQ" type="3008" element="_1HYxYHSJEey81q0uuuC8TQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1HZ_gnSJEey81q0uuuC8TQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1HZ_g3SJEey81q0uuuC8TQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1HZ_gXSJEey81q0uuuC8TQ" x="701" y="210" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ZkxyQXCqEeyXNsFPbLjerQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ZkxyQnCqEeyXNsFPbLjerQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ZkxyQ3CqEeyXNsFPbLjerQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ZkyZUnCqEeyXNsFPbLjerQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZkxyRHCqEeyXNsFPbLjerQ" x="23" y="804" width="1297" height="606"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_g_nJOHCmEeyXNsFPbLjerQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_g_nJOXCmEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_g_nJOnCmEeyXNsFPbLjerQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_g_nJO3CmEeyXNsFPbLjerQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g_nJPHCmEeyXNsFPbLjerQ" width="1470" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_g_nJPXCmEeyXNsFPbLjerQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_g_nJPnCmEeyXNsFPbLjerQ" type="4001" element="_g_nJCHCmEeyXNsFPbLjerQ" source="_g_nJL3CmEeyXNsFPbLjerQ" target="_g_nJLHCmEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g_nJP3CmEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g_nJQHCmEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g_nJQXCmEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g_nJQnCmEeyXNsFPbLjerQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WCRxUXCpEeyXNsFPbLjerQ" type="4001" element="_WCRKQHCpEeyXNsFPbLjerQ" source="_g_nJLHCmEeyXNsFPbLjerQ" target="_WCMRwHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WCSYYHCpEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WCSYYXCpEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WCRxUnCpEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WCRxU3CpEeyXNsFPbLjerQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ardi8HCpEeyXNsFPbLjerQ" type="4001" element="_arc74HCpEeyXNsFPbLjerQ" source="_WCMRwHCpEeyXNsFPbLjerQ" target="_wtsNQHSJEey81q0uuuC8TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_areKAHCpEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_areKAXCpEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ardi8XCpEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ardi8nCpEeyXNsFPbLjerQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_chOKsHCpEeyXNsFPbLjerQ" type="4001" element="_chNjoHCpEeyXNsFPbLjerQ" source="_wtsNQHSJEey81q0uuuC8TQ" target="_chIEEHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_chOKs3CpEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_chOKtHCpEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_chOKsXCpEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_chOKsnCpEeyXNsFPbLjerQ" points="[0, 22, 264, -117]$[0, 71, 264, -68]$[-208, 71, 56, -68]$[-208, 109, 56, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fOebInCpEeyXNsFPbLjerQ" type="4001" element="_fOd0EHCpEeyXNsFPbLjerQ" source="_wtsNQHSJEey81q0uuuC8TQ" target="_TaY14HPGEeySYZ5sg-RwCQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fOfCMHCpEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fOfCMXCpEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fOebI3CpEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fOebJHCpEeyXNsFPbLjerQ" points="[-7, -14, -602, -23]$[-7, -51, -602, -60]$[641, -51, 46, -60]$[641, -14, 46, -23]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Knfc4HPGEeySYZ5sg-RwCQ" id="(0.04,0.46)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uyp6sHCpEeyXNsFPbLjerQ" type="4001" element="_uyoskHCpEeyXNsFPbLjerQ" source="_wtsNQHSJEey81q0uuuC8TQ" target="_uyj0EHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uyqhwHCpEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uyqhwXCpEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uyp6sXCpEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uyp6snCpEeyXNsFPbLjerQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_49Bc8HCpEeyXNsFPbLjerQ" type="4001" element="_49A14HCpEeyXNsFPbLjerQ" source="__6NcEHCqEeyXNsFPbLjerQ" target="_xl0vIHSJEey81q0uuuC8TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_49CEAHCpEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_49CEAXCpEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_49Bc8XCpEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_49Bc8nCpEeyXNsFPbLjerQ" points="[-36, 35, 13, -110]$[-36, 136, 13, -9]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5q0-IHCpEeyXNsFPbLjerQ" type="4001" element="_5q0XEHCpEeyXNsFPbLjerQ" source="_xl0vIHSJEey81q0uuuC8TQ" target="_fOZioHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5q1lMHCpEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5q1lMXCpEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5q0-IXCpEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5q0-InCpEeyXNsFPbLjerQ" points="[-6, 1, -206, -1]$[185, 1, -15, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5q3aYHCpEeyXNsFPbLjerQ" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_69OaIHCpEeyXNsFPbLjerQ" type="4001" element="_69NzEHCpEeyXNsFPbLjerQ" source="_xl0vIHSJEey81q0uuuC8TQ" target="_chIEEHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_69PBMHCpEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_69PBMXCpEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_69OaIXCpEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_69OaInCpEeyXNsFPbLjerQ" points="[-1, -8, 23, 208]$[-31, -204, -7, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_69Q2YHCpEeyXNsFPbLjerQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_69Q2YXCpEeyXNsFPbLjerQ" id="(0.43,0.76)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FkFrIHCqEeyXNsFPbLjerQ" type="4001" element="_FkEdAHCqEeyXNsFPbLjerQ" source="_EF4nwHCqEeyXNsFPbLjerQ" target="__6NcEHCqEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FkGSMHCqEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FkGSMXCqEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FkFrIXCqEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FkFrInCqEeyXNsFPbLjerQ" points="[0, 0, -35, -62]$[105, 94, 70, 32]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FkHgUHCqEeyXNsFPbLjerQ" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oIghcHCqEeyXNsFPbLjerQ" type="4001" element="_oIfTUHCqEeyXNsFPbLjerQ" source="_IO_yMHCqEeyXNsFPbLjerQ" target="_0c9GqHPAEeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oIhIgHCqEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oIhIgXCqEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oIghcXCqEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oIghcnCqEeyXNsFPbLjerQ" points="[0, 0, 107, -462]$[0, 341, 107, -121]$[-120, 341, -13, -121]$[-120, 455, -13, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oIi9sHCqEeyXNsFPbLjerQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oIi9sXCqEeyXNsFPbLjerQ" id="(0.575,0.11666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BSBjknCrEeyXNsFPbLjerQ" type="4001" element="_BSA8gHCrEeyXNsFPbLjerQ" source="__QUxlHCqEeyXNsFPbLjerQ" target="_F1jZI3CrEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BSCKoHCrEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BSCKoXCrEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BSBjk3CrEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BSBjlHCrEeyXNsFPbLjerQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CNgUYHCrEeyXNsFPbLjerQ" type="4001" element="_CNfGQHCrEeyXNsFPbLjerQ" source="_F1jZI3CrEeyXNsFPbLjerQ" target="_CNa00HCrEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CNgUY3CrEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CNgUZHCrEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CNgUYXCrEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CNgUYnCrEeyXNsFPbLjerQ" points="[26, 21, -817, -2]$[828, 21, -15, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-vA0AHO6EeyZqK-Za-7q-g" id="(0.3953488372093023,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DZfmYHCrEeyXNsFPbLjerQ" type="4001" element="_DZe_UHCrEeyXNsFPbLjerQ" source="_F1jZI3CrEeyXNsFPbLjerQ" target="_vl8G7HCrEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DZfmY3CrEeyXNsFPbLjerQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DZgNcHCrEeyXNsFPbLjerQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DZfmYXCrEeyXNsFPbLjerQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DZfmYnCrEeyXNsFPbLjerQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NiOJoHO7EeyZqK-Za-7q-g" type="4001" element="_NiKfQHO7EeyZqK-Za-7q-g" source="_wBHnAHCrEeyXNsFPbLjerQ" target="_NiAuQHO7EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NiOwsHO7EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NiOwsXO7EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NiOJoXO7EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NiOJonO7EeyZqK-Za-7q-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_U_41EHO7EeyZqK-Za-7q-g" type="4001" element="_U_4OAHO7EeyZqK-Za-7q-g" source="_NiAuQHO7EeyZqK-Za-7q-g" target="_1HZ_gHSJEey81q0uuuC8TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_U_5cIHO7EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_U_5cIXO7EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_U_41EXO7EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_U_41EnO7EeyZqK-Za-7q-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_b9EpoHO7EeyZqK-Za-7q-g" type="4001" element="_b9ECkHO7EeyZqK-Za-7q-g" source="_1HZ_gHSJEey81q0uuuC8TQ" target="_b89U4HO7EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_b9FQsHO7EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_b9FQsXO7EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_b9EpoXO7EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_b9EponO7EeyZqK-Za-7q-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r0jfsHO7EeyZqK-Za-7q-g" type="4001" element="_r0hqgHO7EeyZqK-Za-7q-g" source="_o2B5EHO7EeyZqK-Za-7q-g" target="_NX56kHO8EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r0jfs3O7EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r0jftHO7EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r0jfsXO7EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r0jfsnO7EeyZqK-Za-7q-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jErwEHO8EeyZqK-Za-7q-g" type="4001" element="_jEqh8HO8EeyZqK-Za-7q-g" source="_ySirMHSJEey81q0uuuC8TQ" target="_y54_EHSJEey81q0uuuC8TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jErwE3O8EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jErwFHO8EeyZqK-Za-7q-g" x="7" y="-30"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jErwEXO8EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jErwEnO8EeyZqK-Za-7q-g" points="[0, 0, -117, 110]$[112, -111, -5, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jEuMUHO8EeyZqK-Za-7q-g" id="(0.7906976744186046,0.5581395348837209)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jEuMUXO8EeyZqK-Za-7q-g" id="(0.627906976744186,0.16279069767441862)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ltnhMHO8EeyZqK-Za-7q-g" type="4001" element="_ltmTEHO8EeyZqK-Za-7q-g" source="_NX56kHO8EeyZqK-Za-7q-g" target="_z0rzY3SJEey81q0uuuC8TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ltoIQHO8EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ltoIQXO8EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ltnhMXO8EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ltnhMnO8EeyZqK-Za-7q-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mgJxYHO8EeyZqK-Za-7q-g" type="4001" element="_mgIjQHO8EeyZqK-Za-7q-g" source="_z0rzY3SJEey81q0uuuC8TQ" target="_y54_EHSJEey81q0uuuC8TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mgKYcHO8EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mgKYcXO8EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mgJxYXO8EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mgJxYnO8EeyZqK-Za-7q-g" points="[-5, 31, 93, 33]$[-5, 51, 93, 53]$[-100, 51, -2, 53]$[-100, 6, -2, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mgM0sHO8EeyZqK-Za-7q-g" id="(0.4418604651162791,0.09302325581395349)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_z81HAHO-EeyZqK-Za-7q-g" id="(0.5348837209302325,0.813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nfH7EHO8EeyZqK-Za-7q-g" type="4001" element="_nfGF4HO8EeyZqK-Za-7q-g" source="_z0rzY3SJEey81q0uuuC8TQ" target="_0c9GqHPAEeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nfH7E3O8EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nfH7FHO8EeyZqK-Za-7q-g" x="41" y="12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nfH7EXO8EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nfH7EnO8EeyZqK-Za-7q-g" points="[-26, 10, 429, -268]$[-26, 180, 429, -98]$[-480, 180, -25, -98]$[-480, 275, -25, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nfKXUHO8EeyZqK-Za-7q-g" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nfKXUXO8EeyZqK-Za-7q-g" id="(0.8333333333333334,0.05)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6L3HAHO8EeyZqK-Za-7q-g" type="4001" element="_6L2f8HO8EeyZqK-Za-7q-g" source="_1HZ_gHSJEey81q0uuuC8TQ" target="_NX56kHO8EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6L3uEHO8EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6L3uEXO8EeyZqK-Za-7q-g" x="-86" y="19"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6L3HAXO8EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6L3HAnO8EeyZqK-Za-7q-g" points="[-22, -26, -61, 279]$[20, -26, -19, 279]$[20, -296, -19, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6L5jQHO8EeyZqK-Za-7q-g" id="(0.8604651162790697,0.16279069767441862)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6L6KUHO8EeyZqK-Za-7q-g" id="(0.5125,0.8875)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ImAcYHO9EeyZqK-Za-7q-g" type="4001" element="_Il_OQHO9EeyZqK-Za-7q-g" source="_z0rzY3SJEey81q0uuuC8TQ" target="_fOZioHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ImAcY3O9EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ImBDcHO9EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ImAcYXO9EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ImAcYnO9EeyZqK-Za-7q-g" points="[-22, -30, -564, 182]$[14, -30, -528, 182]$[14, -69, -528, 143]$[542, -69, 0, 143]$[542, -198, 0, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ImC4oHO9EeyZqK-Za-7q-g" id="(0.8372093023255814,0.20930232558139536)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cRXzwHO9EeyZqK-Za-7q-g" type="4001" element="_cRUJYHO9EeyZqK-Za-7q-g" source="_ySirMHSJEey81q0uuuC8TQ" target="_fOZioHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cRXzw3O9EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cRXzxHO9EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cRXzwXO9EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cRXzwnO9EeyZqK-Za-7q-g" points="[21, -1, -797, 108]$[21, -61, -797, 48]$[771, -61, -47, 48]$[771, -102, -47, 7]$[804, -102, -14, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mCxcYHO9EeyZqK-Za-7q-g" id="(0.46511627906976744,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ft8BQHO9EeyZqK-Za-7q-g" type="4001" element="_ft6zIHO9EeyZqK-Za-7q-g" source="_ySirMHSJEey81q0uuuC8TQ" target="_0c9GqHPAEeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ft8oUHO9EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ft8oUXO9EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ft8BQXO9EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ft8BQnO9EeyZqK-Za-7q-g" points="[-3, 2, 262, -376]$[-285, 2, -20, -376]$[-285, 377, -20, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ft-dgHO9EeyZqK-Za-7q-g" id="(0.06976744186046512,0.4418604651162791)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ft-dgXO9EeyZqK-Za-7q-g" id="(0.31666666666666665,0.016666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jD3bQHO9EeyZqK-Za-7q-g" type="4001" element="_jD20MHO9EeyZqK-Za-7q-g" source="_M0AjUHO8EeyZqK-Za-7q-g" target="_ySirMHSJEey81q0uuuC8TQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jD4CUHO9EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jD4CUXO9EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jD3bQXO9EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jD3bQnO9EeyZqK-Za-7q-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0qt9MHO9EeyZqK-Za-7q-g" type="4001" element="_0qsvEHO9EeyZqK-Za-7q-g" source="_1HZ_gHSJEey81q0uuuC8TQ" target="_0qmocHO9EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0qukQHO9EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0qukQXO9EeyZqK-Za-7q-g" x="51" y="-26"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0qt9MXO9EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0qt9MnO9EeyZqK-Za-7q-g" points="[-10, -11, 141, 158]$[-10, -170, 141, -1]$[-101, -170, 50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_46KZIHO9EeyZqK-Za-7q-g" type="4001" element="_46JLAHO9EeyZqK-Za-7q-g" source="_0qmocHO9EeyZqK-Za-7q-g" target="_M0AjUHO8EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_46KZI3O9EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_46KZJHO9EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_46KZIXO9EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_46KZInO9EeyZqK-Za-7q-g" points="[-100, -2, 105, 117]$[-199, -2, 6, 117]$[-199, -115, 6, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_46M1YHO9EeyZqK-Za-7q-g" id="(1.0,0.54)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_46M1YXO9EeyZqK-Za-7q-g" id="(0.43,0.92)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LPPdknO_EeyZqK-Za-7q-g" type="4001" element="_LPO2gHO_EeyZqK-Za-7q-g" source="_y54_EHSJEey81q0uuuC8TQ" target="_3_wUeHO_EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LPQEoHO_EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LPQEoXO_EeyZqK-Za-7q-g" x="-535" y="580"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LPPdk3O_EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LPPdlHO_EeyZqK-Za-7q-g" points="[22, 0, 434, -761]$[621, 0, 1033, -761]$[621, 761, 1033, 0]$[-362, 761, 50, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dcuhsHO_EeyZqK-Za-7q-g" type="4001" element="_dctTkHO_EeyZqK-Za-7q-g" source="_y54_EHSJEey81q0uuuC8TQ" target="_h261EHO_EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dcuhs3O_EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dcuhtHO_EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dcuhsXO_EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dcuhsnO_EeyZqK-Za-7q-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_in9QcHO_EeyZqK-Za-7q-g" type="4001" element="_in8pYHO_EeyZqK-Za-7q-g" source="_h261EHO_EeyZqK-Za-7q-g" target="_4Vbph3O_EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_in9Qc3O_EeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_in9QdHO_EeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_in9QcXO_EeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_in9QcnO_EeyZqK-Za-7q-g" points="[60, 30, -419, -536]$[417, 30, -62, -536]$[417, 565, -62, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_s4Qh4HSLEey81q0uuuC8TQ" id="(0.9833333333333333,0.65)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oehbMHO_EeyZqK-Za-7q-g" id="(0.68,0.02)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DNtaoHPAEeyZqK-Za-7q-g" type="4001" element="_DNsMgHPAEeyZqK-Za-7q-g" source="_4Vbph3O_EeyZqK-Za-7q-g" target="_EIN7EHPAEeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DNtao3PAEeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DNtapHPAEeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DNtaoXPAEeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DNtaonPAEeyZqK-Za-7q-g" points="[-22, -30, 149, 198]$[-22, -239, 149, -11]$[-111, -239, 60, -11]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JMklwHPAEeyZqK-Za-7q-g" type="4001" element="_JMj-sHPAEeyZqK-Za-7q-g" source="_EIN7EHPAEeyZqK-Za-7q-g" target="_KBD9wHPAEeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JMklw3PAEeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JMklxHPAEeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JMklwXPAEeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JMklwnPAEeyZqK-Za-7q-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KjFswHPAEeyZqK-Za-7q-g" type="4001" element="_Ki8i0HPAEeyZqK-Za-7q-g" source="_KBD9wHPAEeyZqK-Za-7q-g" target="_fOZioHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KjFsw3PAEeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KjFsxHPAEeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KjFswXPAEeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KjFswnPAEeyZqK-Za-7q-g" points="[0, -7, -239, 325]$[262, -7, 23, 325]$[262, -332, 23, 0]$[254, -332, 15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KjIJAHPAEeyZqK-Za-7q-g" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g36ZsHPAEeyZqK-Za-7q-g" type="4001" element="_g3uzgHPAEeyZqK-Za-7q-g" source="_KBD9wHPAEeyZqK-Za-7q-g" target="_3_wUeHO_EeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g36Zs3PAEeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g37AwHPAEeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g36ZsXPAEeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g36ZsnPAEeyZqK-Za-7q-g" points="[-43, -7, 784, -530]$[-898, -7, -71, -530]$[-898, 554, -71, 31]$[-878, 554, -51, 31]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g3818HPAEeyZqK-Za-7q-g" id="(0.5813953488372093,0.023255813953488372)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g3818XPAEeyZqK-Za-7q-g" id="(0.31875,0.1125)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8iTdIHPAEeyZqK-Za-7q-g" type="4001" element="_8iSPAHPAEeyZqK-Za-7q-g" source="_0c9GqHPAEeyZqK-Za-7q-g" target="__QUxlHCqEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8iUEMHPAEeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8iUEMXPAEeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8iTdIXPAEeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8iTdInPAEeyZqK-Za-7q-g" points="[-61, 31, 13, -123]$[-61, 147, 13, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8iWgcHPAEeyZqK-Za-7q-g" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8iWgcXPAEeyZqK-Za-7q-g" id="(0.475,0.11666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ACqwEHPCEeyZqK-Za-7q-g" type="4001" element="_ACph8HPCEeyZqK-Za-7q-g" source="_3ghI0HPBEeyZqK-Za-7q-g" target="_B4mW93PCEeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ACqwE3PCEeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ACqwFHPCEeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ACqwEXPCEeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ACqwEnPCEeyZqK-Za-7q-g" points="[-13, 0, -1183, 452]$[-13, 47, -1183, 499]$[1149, 47, -21, 499]$[1149, -444, -21, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ACtMUHPCEeyZqK-Za-7q-g" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ACtMUXPCEeyZqK-Za-7q-g" id="(0.5166666666666667,0.8666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Go6EQHPCEeyZqK-Za-7q-g" type="4001" element="_Go5dMHPCEeyZqK-Za-7q-g" source="_B4mW93PCEeyZqK-Za-7q-g" target="_fOZioHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Go6EQ3PCEeyZqK-Za-7q-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Go6ERHPCEeyZqK-Za-7q-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Go6EQXPCEeyZqK-Za-7q-g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Go6EQnPCEeyZqK-Za-7q-g" points="[-26, -26, 162, 480]$[-26, -510, 162, -4]$[-182, -510, 6, -4]$[-182, -507, 6, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Go8ggHPCEeyZqK-Za-7q-g" id="(1.0,0.37142857142857144)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_H2gf0HPCEeyZqK-Za-7q-g" id="(0.3,0.03333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_N7MpUHPGEeySYZ5sg-RwCQ" type="4001" element="_N7K0IHPGEeySYZ5sg-RwCQ" source="_TaY14HPGEeySYZ5sg-RwCQ" target="_fOZioHCpEeyXNsFPbLjerQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_N7NQYHPGEeySYZ5sg-RwCQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_N7NQYXPGEeySYZ5sg-RwCQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_N7MpUXPGEeySYZ5sg-RwCQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_N7MpUnPGEeySYZ5sg-RwCQ" points="[-6, 8, -4, -107]$[-6, 58, -4, -57]$[-3, 58, -1, -57]$[-3, 115, -1, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N7QTsHPGEeySYZ5sg-RwCQ" id="(0.44,0.84)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N7QTsXPGEeySYZ5sg-RwCQ" id="(0.23333333333333334,0.06666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_boLEsHSMEey81q0uuuC8TQ" type="4001" element="_boB6wHSMEey81q0uuuC8TQ" source="_KBD9wHPAEeyZqK-Za-7q-g" target="_0c9GqHPAEeyZqK-Za-7q-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_boLrwHSMEey81q0uuuC8TQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_boLrwXSMEey81q0uuuC8TQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_boLEsXSMEey81q0uuuC8TQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_boLEsnSMEey81q0uuuC8TQ" points="[-43, -7, 704, -187]$[-248, -7, 499, -187]$[-248, 124, 499, -56]$[-764, 124, -17, -56]$[-764, 153, -17, -27]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_boOIAHSMEey81q0uuuC8TQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_boOvEHSMEey81q0uuuC8TQ" id="(0.925,0.45)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
